// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using asp.net_core_web_api_reference_project.Data;

#nullable disable

namespace asp.net_core_web_api_reference_project.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20241206210950_seeding data for difficulties and regions")]
    partial class seedingdatafordifficultiesandregions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("asp.net_core_web_api_reference_project.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd4e2ab8-c12e-4ecd-aa38-2cb05f65f518"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("e8cfd57f-247e-416a-bd2c-7c71dd0ccc32"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("10d6c1fe-e783-4649-88b6-a1d895c04a34"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("asp.net_core_web_api_reference_project.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51b3adc3-d4b1-4e3b-8d94-a3d623b56c82"),
                            Code = "RBL",
                            Name = "RAEBARELI",
                            RegionImageUrl = "https://cdn.s3waas.gov.in/s3e3796ae838835da0b6f6ea37bcf8bcb7/uploads/2018/07/2018072687.jpg"
                        },
                        new
                        {
                            Id = new Guid("f347a2a8-978b-4c5a-89c4-62f01ed716f2"),
                            Code = "LKO",
                            Name = "LUCKNOW",
                            RegionImageUrl = "https://t4.ftcdn.net/jpg/05/13/77/31/240_F_513773104_G7Pin2bxWwpMAWqI5MIvrSnWDpYs80WN.jpg"
                        },
                        new
                        {
                            Id = new Guid("757c096c-97e9-4cb1-8b80-f212b140c12c"),
                            Code = "DL",
                            Name = "DELHI",
                            RegionImageUrl = "https://deih43ym53wif.cloudfront.net/Rajpath-delhi-shutterstock_1195751923.jpg_7647e1aad2.jpg"
                        },
                        new
                        {
                            Id = new Guid("2570dcb7-1bd1-47b1-bc02-8bbcd82f2d08"),
                            Code = "NOIDA",
                            Name = "NOIDA"
                        });
                });

            modelBuilder.Entity("asp.net_core_web_api_reference_project.Models.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("LengthInKm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalkImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("asp.net_core_web_api_reference_project.Models.Walk", b =>
                {
                    b.HasOne("asp.net_core_web_api_reference_project.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asp.net_core_web_api_reference_project.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
